-- Active: 1681837025543@@127.0.0.1@3306
CREATE TABLE videos (
    id TEXT PRIMARY KEY UNIQUE NOT NULL,
    title TEXT NOT NULL,
    duration INTEGER NOT NULL,
    upload TEXT NOT NULL
);

SELECT * FROM videos;

DROP TABLE videos;